"""Create pf history table.

Revision ID: 00f2f6f12466
Revises: 2a17545c86bb
Create Date: 2025-07-10 12:09:13.384691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00f2f6f12466'
down_revision: Union[str, None] = '2a17545c86bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_portfolio_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value_in_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_portfolio_history_user_id'), 'user_portfolio_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_portfolio_history_user_id'), table_name='user_portfolio_history')
    op.drop_table('user_portfolio_history')
    # ### end Alembic commands ###
