"""Create dtao history table.

Revision ID: 05df7c68afec
Revises: 3c35ce39771a
Create Date: 2025-07-02 15:17:36.134673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05df7c68afec'
down_revision: Union[str, None] = '3c35ce39771a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dtao_history',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('cg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('cg_id', 'date')
    )
    op.create_index(op.f('ix_dtao_history_cg_id'), 'dtao_history', ['cg_id'], unique=False)
    op.create_index(op.f('ix_dtao_history_date'), 'dtao_history', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dtao_history_date'), table_name='dtao_history')
    op.drop_index(op.f('ix_dtao_history_cg_id'), table_name='dtao_history')
    op.drop_table('dtao_history')
    # ### end Alembic commands ###
