"""Update asset table with qty_by_wallet

Revision ID: 2b75e6eebf3e
Revises: fdb90abc0094
Create Date: 2025-08-05 15:35:19.067088

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2b75e6eebf3e'
down_revision: Union[str, None] = 'fdb90abc0094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('qty_by_wallet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'qty_by_wallet')
    # ### end Alembic commands ###
