"""create dtao history table.

Revision ID: 6fdba4e3f95c
Revises: 7da70bf445be
Create Date: 2025-06-19 11:53:14.680096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fdba4e3f95c'
down_revision: Union[str, None] = '7da70bf445be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dtaohistory',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('netuid', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_dtaohistory_date'), 'dtaohistory', ['date'], unique=False)
    op.create_index(op.f('ix_dtaohistory_netuid'), 'dtaohistory', ['netuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dtaohistory_netuid'), table_name='dtaohistory')
    op.drop_index(op.f('ix_dtaohistory_date'), table_name='dtaohistory')
    op.drop_table('dtaohistory')
    # ### end Alembic commands ###
