"""Update token table with new columns.

Revision ID: 7da70bf445be
Revises: 35436faa3e0f
Create Date: 2025-06-16 13:17:38.391355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7da70bf445be'
down_revision: Union[str, None] = '35436faa3e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tokens_symbol'), 'tokens', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_symbol'), table_name='tokens')
    # ### end Alembic commands ###
