"""Create dtao list table.

Revision ID: 867c0fc25fb0
Revises: 05df7c68afec
Create Date: 2025-07-04 08:58:09.744133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '867c0fc25fb0'
down_revision: Union[str, None] = '05df7c68afec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dtao_list',
    sa.Column('cg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('cg_id')
    )
    op.create_index(op.f('ix_dtao_list_symbol'), 'dtao_list', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dtao_list_symbol'), table_name='dtao_list')
    op.drop_table('dtao_list')
    # ### end Alembic commands ###
